function catalog=gasCatalog()
%GASCATALOG Built-in fluids, accepted names and bundled REFPROP table files.
% Adding a fluid also requires its Ideal/RK parameters and offline data.
catalog=struct( ...
    'Name',{"Helium","Hydrogen","Nitrogen","Argon","Air","CarbonDioxide"}, ...
    'Aliases',{["he","he4","he-4","helium"],["h2","hydrogen"], ...
        ["n2","nitrogen"],["ar","argon"],"air", ...
        ["co2","co₂","carbon dioxide","carbon-dioxide","carbondioxide"]}, ...
    'TabularFile',{"helium-refprop.mat","hydrogen-refprop.mat", ...
        "nitrogen-refprop.mat","argon-refprop.mat","air-refprop.mat", ...
        "carbon-dioxide-refprop.mat"});
end
