function catalog=modelCatalog()
%MODELCATALOG Return the selectable gas-model families and their scope.
%   IDs are accepted by gas.withEquationOfState(ID). Display names are
%   also accepted for the four names below.

catalog=struct( ...
    'Id',{"ideal","rk","tabular","helmholtz"}, ...
    'Name',{"Ideal Gas","RK Gas","Tabular Gas","NIST He-4 Helmholtz"}, ...
    'Algorithm',{ ...
        "p = rho*R*T with constant ideal-gas heat capacities", ...
        "Redlich-Kwong cubic EOS with consistent departure functions", ...
        "SAGE Z(v,T) table with C1 bicubic Hermite interpolation", ...
        "NIST He-4 Helmholtz fundamental equation"}, ...
    'Scope',{ ...
        "Configured gases: He, H2, N2, Ar, Air", ...
        "Pure He, H2, N2 or Ar above the critical temperature", ...
        "Any gas whose supplied table matches its R and molar mass", ...
        "Helium only"});
end
