function catalog=modelCatalog()
%MODELCATALOG Return the selectable gas-model families and their scope.
%   IDs are accepted by gas.withEquationOfState(ID). Display names are
%   also accepted for the four names below.

catalog=struct( ...
    'Id',{"ideal","rk","tabular","helmholtz"}, ...
    'Name',{"Ideal Gas","RK Gas","Tabular Gas","NIST He-4 Helmholtz"}, ...
    'Algorithm',{ ...
        "p = rho*R*T with constant ideal-gas heat capacities", ...
        "Redlich-Kwong coefficients with consistent departure functions", ...
        "SAGE Z(v,T) table with C1 bicubic Hermite interpolation", ...
        "NIST He-4 Helmholtz fundamental equation"}, ...
    'Scope',{ ...
        "Configured gases: He, H2, N2, Ar, Air, CO2", ...
        "He, H2, N2, Ar, pseudo-pure Air and CO2 within declared gas-phase limits", ...
        "Bundled He, H2, N2, Ar, Air, CO2; custom tables matching gas properties", ...
        "Helium only"});
end
