function [value,temperatureDerivative,volumeDerivative]=interpolate(surface,v,T)
%INTERPOLATE Evaluate one C1 bicubic tabular surface within its coverage.
if any(v(:)<surface.SpecificVolumeM3PerKg(1) | ...
        v(:)>surface.SpecificVolumeM3PerKg(end) | ...
        T(:)<surface.TemperatureK(1) | T(:)>surface.TemperatureK(end))
    error('gasprop:TabularRange', ...
        'Tabular Gas state is outside the supplied v-T table range.');
end
[value,temperatureDerivative,volumeDerivative]= ...
    gasprop.eos.tabular.evaluateSurface(surface,T,v);
end
