function result=state(table,R,T,rho)
%STATE Evaluate the complete current real-gas contract from table splines.
shape=size(T+rho); %#ok<ELARLOG> Deliberate scalar expansion to common state shape.
T=reshape(T+zeros(shape),1,[]); rho=reshape(rho+zeros(shape),1,[]);
v=1./rho;
[z,zT,zV]=gasprop.eos.tabular.interpolate( ...
    table.CompressibilitySurface,v,T);
[u,cv]=gasprop.eos.tabular.interpolate( ...
    table.InternalEnergySurface,v,T);
entropy=gasprop.eos.tabular.interpolate(table.EntropySurface,v,T);
p=R.*T.*z./v;
pT=R.*(z+T.*zT)./v;
pRho=R.*T.*(z-v.*zV);
cp=cv+T.*pT.^2./(rho.^2.*pRho);
soundSquared=pRho+T.*pT.^2./(rho.^2.*cv);
if any(~isfinite(p) | ~isfinite(u) | ~isfinite(cv) | ~isfinite(cp) | ...
        p<=0 | cv<=0 | cp<=0 | pRho<=0 | soundSquared<=0)
    error('gasprop:TabularState', ...
        'Tabular interpolation produced an invalid or unstable thermodynamic state.');
end
result=struct('Pressure',reshape(p,shape), ...
    'InternalEnergy',reshape(u,shape), ...
    'Enthalpy',reshape(u+p./rho,shape), ...
    'Entropy',reshape(entropy,shape), ...
    'Cv',reshape(cv,shape),'Cp',reshape(cp,shape), ...
    'PressureTemperatureDerivative',reshape(pT,shape), ...
    'PressureDensityDerivative',reshape(pRho,shape), ...
    'SoundSpeed',reshape(sqrt(soundSquared),shape), ...
    'Z',reshape(z,shape),'R',R,'Density',reshape(rho,shape));
end
